---
title: BIO8075 Course Handbook Systematic Review and Meta-analysis in Ecology and
  Conservation
author: "Roy Sanderson"
date: "03/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Introduction

This handbook gives you an overview of BIO8075 Systematic review and meta-analysis in ecology and conservation. In particular, it explains the philosophical rationale behind the course, why we believe it is important for those working in ecology & conservation to understand these concepts, and to provide you with insights into the content and structure of the course. First, let us go back in time...

_It is necessary, while formulating the problems of which in our advance we are to find the solutions, to call into council the views of those of our predecessors who have declared an opinion on the subject, in order that we may profit by whatever is sound in their suggestions and avoid their errors._

Aristotle, _De Anima, Book 1, chapter 2_

So, people have realised that it is useful to look at previously published work for centuries in order to build on an existing body of knowledge, even if the concepts of "systematic review" and "meta-analysis" are much more recent. Indeed, whilst it is fairly obvious that, as Issac Newton famously said, we "stand on the shoulders of giants", how do we determine the reliability of previously published research. If this module was running in the year 1020 CE rather than 2020 CE, most European "publications", if they could be called that, categorically stated that the Earth was flat! Fortunately Arabic, Indian and Chinese philosophers had already spotted this was not true.

Modern methods of systematic review and meta-analysis were driven primarily in medicine, especially through organisations such as [Cochrane Collaboration](https://www.cochrane.org/) which was founded in 1993 as a means to improve decision-making in evidence-based medicine. Cochrane Collaboration developed a standard, rigorous protocol for undertaking reviews of the scientific literature, in particular **systematic reviews**. This in turn allowed statistical analyses to be used on the findings of multiple peer-reviewed scientific papers, a process known as **meta-analysis** to distinguish it from conventional statistical models of single studies. These two approaches, systematic reviews, often supplemented by meta-analysis, greatly improved the quality of decision-making in medicine, so that the appropriate life-saving interventions could be implemented. When people's lives depend on making the right decision, a single research paper is insufficient: we need to draw on the whole body of scientific knowledge in an appropriate way.

# 2. Systematic reviews and meta-analysis in ecology and conservation
Whilst the benefits of systematic reviews and meta-analysis have been well-established in medical disciplines, their uptake in ecology and conservation has been much slower, and it is only over the last 5 years that its importance has been recognised. Part of the problem has been poor reporting in the scientific literature of research findings: if Methods and Results are inadequately described, it is difficult to "pool" findings from multiple papers in order to undertake a formal meta-analysis. Most of the books and papers describing systematic reviews and meta-analysis were published from a health or social-science perspective, rather than ecology and biodiversity, and hence often used terminology unfamiliar to scientists from ecology. Most software for managing large bibliographic databases of literature was expensive, and the software for meta-analysis was only available commercially. Whilst many of these problems still exist, recently there have been major changes that benefit ecologists and conservationists:

* Availability of substantial texts, and peer-reviewed papers, on the theory and practice of systematic review and meta-analysis, written from the perspective of environmental scientists
* More rigorous requirements by many scientific journals on reporting standards. These vary from making available any code used in the analyses, to free access to the complete datasets used, so that other scientists can repeat the analyses and check the **reproducibility** of the findings.
* High quality open-source (free) systems to manage bibliographic databases. Thus, in addition to commercial software such as [EndNote](endnote.com), public-domain software such as [Zotero](zotero.org) whilst more limited in functionality, can now serve as a suitable alternative
* The free software [R](www.r-project.org) has been in existance for about 25 years, but within the last five years has been improved with some excellent free add-on "packages", in particular the [metafor](http://www.metafor-project.org/doku.php) which is as powerful, if not more powerful, than many of its commercial rivals.

# 3. Outline of this course
BIO8075 is split into two main parts, first on systematic reviews, and second statistical modelling / meta-analysis. No prior experience of either is assumed. Whilst most students have done **narrative reviews** as part of their undergraduate degrees, the distinct differences from formal systematic reviews, and the requirements of the latter, and rarely covered. Similarly, most students from a science background (less so from humanities) will have covered basics of statistical analysis as undergraduates. However, experience has shown us that whilst some students may have heard of terms such as 'variance', 'standard error', 'p-values' etc., their actual understanding of these concepts is often tenuous. We therefore provide a refresher on basic statistics, before moving on to meta-analysis.

## 3.1 Systematic Reviews
### 3.1.1 Question formulation
Defining the "question" or "problem" that you are going to study may seem an obvious first step, but doing this rigorously is absolutely critical to all subsequent stages. Often an initial "pilot" search of the literature is needed in this phase: if your question is too narrowly focussed, you will not obtain enough previously published peer-reviewed papers to do a systematic review. If your question is too broad, you will be swamped with papers, often with incompatible aims and objectives. The most common way of defining your question is PICO :

* **P**roblem - who, or what, is being affected? e.g. habitat, species, ecosystem
* **I**ntervention - what is being done? e.g. a management intervention to conserve species
* **C**omparison - what are you comparing with? e.g. a control group that does not receive the intervention, or several different interventions.
* **O**utcome - what do you want to achieve? e.g. improved survivorship

Using the PICO approach helps you in the critical phase of defining your research question. This might be:

* "Does control of grey squirrels by trapping in a 1 km band around a woodland prevent red squirrels becoming infected by parapox virus?"
* "Is survivorship of coral orchid improved by limiting trampling from livestock?"
* "Does grazing by goats reduce the amount of _Juncus_ infestation of semi-natural wet grassland?"

### 3.1.2 Literature search
You may be familiar with literature searches using Google Scholar or similar, using a slightly haphazard system to locate papers. However, a proper literature search should be so formalised that it is actually **reproducible**. In other words, if another scientist were to follow the same search strategy that you used, over the same years, same search terms, same databases, same inclusion and exclusion criteria, then they should find the identical set of papers. This sounds totally unrealistic at first, but in practice you are probably familiar with the **Methods** section of a conventional scientific paper, e.g. of a field or laboratory experiment. If the paper is written up correctly, and you follow the described methods for the experiment, you should obtain very similar results. The concept is the same for literature searches, and we will discuss the PRISMA approach to reporting your findings.

### 3.1.3 Data evaluation (and extraction)
You need to be able to formally evaluate the findings of the research papers you find. This is the most time-consuming step in the process. Ideally, you should also find a way of extracting information from the papers, and recording this information. At its simplest, a "vote tally" approach can be used, i.e. count up the number of papers that did or did not find a response as a result of the intervention you are investigating. In practice, vote tally approaches are very crude, and more sophisticated methods can be used. If you plan to undertake a formal meta-analysis, then knowing how to extract data, understanding effect sizes, sample sizes etc. is essential.

### 3.1.4 Writing and structuring a systematic review
You will learn about best practice in reporting your systematic review, and also how to communicate your findings to potential policy-makers. "Scientists advise, but ministers decide" is the phrase used in UK Government and Civil Service. Many policy-makers are not trained scientists, and may not have time to read overly long, complex reports, therefore it is essential to be able to communicate concisely, precisely, and with clarity.

### 3.1.5 Perspectives of different 'actors'
Conservation policy is not made in isolation, and there will be many different interest groups and non-governmental organisations with different, sometimes conflicting, interpretations of the scientific question, and the best outcome. You should consider these issues when developing your question at the PICO stage, and throughout the systematic review process. We will use a 'role-play' exercise to consider the topical issue of neonicotinoid insecticides and pollinators in UK agriculture. The pros and cons of allowing or banning the use of these insecticides are less obvious than might first appear, depending on who you are.

## 3.2 Meta-analysis
### 3.2.1 Introduction to R/RStudio and refresher on statistical concepts
We will use the free R/RStudio software for analyses. This part of the course will introduce you to R/RStudio, how to import data, obtain summary statistics, plot simple graphs etc. We will also provide a refresher on basic statistics for those of you who need a reminder, or did not cover, these topics as undergraduates. Interactive online websites will also be available for you to explore some of these concepts, without the need for access to R/Rstudio.

### 3.2.2 Basic goal-oriented philosphy
It is possible that as undergraduates you were taught a whole array of different statistical tests, such as t.tests, pairwise t.tests, chi-squared tests, one-way Anova, two-way Anova, analysis of covariance, linear regression, polynomial regression, logistic regression etc. These all fall within the same type of statistical model, namely the **(generalised) linear model**. It is much easier to think in this way. See [this website](https://lindeloev.github.io/tests-as-linear/) for a nice summary of the idea. Indeed, many people take it one stage further, and make it:

$$\textit{}$$